import Head from 'next/head'
import { CardAbout } from '../src/components/CardAbout'
import { Hello } from '/src/components/Hello'
import { Menu } from '/src/components/Menu'

export default function Home() {
  return (
    <>
      <Head>
        <meta charset="UTF-8" />
        <title>Ewerton Coutinho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-color" content="#000000" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-size-zero">Ewerton Coutinho</h1>
      <Menu></Menu>
      <Hello greeting="Hi, I'm" name="Ewerton" caption="I'm a UX/UI Designer and Full-stack Developer" margin></Hello>
      <CardAbout></CardAbout>
    </>
  )
}
