import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
import Hello from '/src/components/Hello'
import CardAbout from '../src/components/CardAbout'
import Menu from '/src/components/Menu'
import Works from '../src/components/Works'
import Footer from '../src/components/Footer'

export async function getStaticProps({ locale }) {
    return {
        props: {
            ...(await serverSideTranslations(locale, ['home'])),
        },
    }
}

export default function Home() {
    const { t } = useTranslation()
    return (
        <>
            <Head>
                <meta charSet="UTF-8" />
                <title>Ewerton Coutinho</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <meta name="theme-color" content="#000000" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu></Menu>
            <Hello
                greeting={t('home:hello')}
                name="Ewerton"
                caption={t('home:caption')}
            ></Hello>
            <CardAbout
                greeting={t('home:greeting')}
                about={t('home:about')}
            ></CardAbout>
            <Works works={t('home:works')}></Works>
            <Footer touch={t('home:touch')}></Footer>
        </>
    )
}
